---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "docs"
  - "gulpfile.js"
  - "e2e-tests"
  - "app/**/*_tests.js"
  - "reports"
  - "api-tests"
