language: node_js
sudo: required
node_js:
  - "4.2.3"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g gulp
  - gem install sass
  - gem install scss-lint
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - gulp
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Chrome
  - node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=chrome
