language: node_js
sudo: required
node_js:
  - "4.2.3"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    code_climate:
      repo_token: 51453244e4690779bfd8033ced740134217df40f3bdebc574b51831732425fc1

rvm:
  - "2.2"

cache:
  directories:
    - node_modules

install:
  - npm install
  - gem install sass
  - gem install scss-lint
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - npm run gulp
  - npm run karma-q
  - npm run protractor-firefox
  - npm run api-tests
after_success:
  - coveralls
