language: node_js
sudo: required
node_js:
  - "4.2.3"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    code_climate:
        repo_token: 51453244e4690779bfd8033ced740134217df40f3bdebc574b51831732425fc1

rvm:
  - "2.2"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g gulp codeclimate-test-reporter
  - gem install sass
  - gem install scss-lint
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - gulp
  - karma start karma.conf.js --no-auto-watch --single-run --reporters=dots
  - protractor e2e-tests/protractor.conf.js

